on:
  pull_request:
    types:
      - opened

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: SQA
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2 
      with: 
        ref: ${{ github.ref }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        echo "sqa"
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init
        terraform plan -out src/tfplan -var-file="sqa.tfvars.json"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: TerraformPlan
        path: src/tfplan
        retention-days: 5
